#!/bin/bash

# Date:	6/21/2011
# Description:
#	Install build dependencies.

MARK6_ROOT=/home/dlapsley/mark6
EXTERN_ROOT=${MARK6_ROOT}/src/extern

YUM=/usr/bin/yum
TAR=/bin/tar

PREQ="boost141-devel.x86_64 cppunit-devel.x86_64 texinfo.x86_64 texi2html.noarch texinfo-tex.x86_64"
APR=apr-1.4.5
APR_UTIL=apr-util-1.3.12
LOG4CXX=apache-log4cxx-0.10.0

install_binary_deps() {
	echo Installing binary dependencies: ${PREQ}
	sudo ${YUM} install ${PREQ} -y
}

install_source_deps() {
	echo Installing ${APR}...

	cd ${EXTERN_ROOT}
	${TAR} xvzf ${APR}.tar.gz
	cd ${APR}
	./configure --prefix=/usr/local \
		--enable-threads
	make
	sudo make install
	cd ..

	echo Installing ${APR_UTIL}...
	cd ${EXTERN_ROOT}
	${TAR} xvzf ${APR_UTIL}.tar.gz
	cd ${APR_UTIL}
	./configure --prefix=/usr/local \
		--with-apr=../${APR}
	make
	sudo make install
	cd ..

	echo Installing ${LOG4CXX}...
	cd ${EXTERN_ROOT}
	${TAR} xvzf ${LOG4CXX}.tar.gz
	cd ${LOG4CXX}
	./configure --prefix=/usr/local \
		--with-apr-util=../${APR_UTIL}
	make
	sudo make install
	cd ..

}

install_binary_deps
#install_source_deps

export MARK6_ROOT

./bootstrap
./configure --prefix=/opt/haystack/mark6 \
	BOOST_LIBDIR=/usr/lib64/boost141 \
	BOOST_INCDIR=/usr/include/boost141
