#!/usr/bin/python

# Copyright 2011 MIT Haystack Observatory
# 
# This file is part of Mark6.
# 
# Mark6 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2 of the License.
# 
# Mark6 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Mark6.  If not, see <http://www.gnu.org/licenses/>.

import subprocess
import time
import sys
import optparse
from xml.etree.ElementTree import ElementTree
import datetime

class Session:

	polling_interval = 0.1

	def __init__(self, scan_list):
		self._scan_list = scan_list

	def execute(self, dryrun=False):
		for s in self._scan_list:
			if s.late():
				print 'skipping late scan ', time.time(), s
				continue

			print s
			sleep_time = s._duration
			print 'args', s.args()

			while time.time() < s._start_time:
				time.sleep(Session.polling_interval)

			print 'start', time.time(), s._start_time

			start_time = time.time()
			if not dryrun:
				p = subprocess.Popen(s.args())
				p.wait()	
			else:
				time.sleep(s._duration)

			duration = time.time() - start_time
			print 'duration', sleep_time, duration
			print '\n',

class Scan:

	mark6_exec = '/opt/mit/mark6/bin/net2raid-run'

	def __init__(self, experiment_name, source, station_code, start_time,
		     duration, scan_name):
		self._experiment_name = experiment_name
		self._source = source
		self._station_code = station_code
		self._start_time = int(start_time)
		self._duration = int(duration)
		self._end_time = self._start_time + self._duration
		self._scan_name = scan_name

        def __str__(self):
                return ''.join([
                        '<scan ',
                        'experiment="%s" '%self._experiment_name,
                        'source="%s" '%self._source,
                        'station_code="%s" '%self._station_code,
                        'start_time="%d" '%self._start_time,
                        'duration="%d" '%self._duration,
                        'scan_name="%s"'%self._scan_name,
                        '/>'
                        ])

	def args(self):
		return [ Scan.mark6_exec, self._scan_name,
			str(self._start_time), str(self._duration) ]

	def late(self):
		if time.time() > self._end_time:
			return True
		return False	



def test():
	print 'Running test schedule.'
	now = time.time()
	TEST_SCANS = [
		('4242', 'WESTFORD', now+60, 5),
		('4243', 'WESTFORD', now+20, 7),
		('4244', 'WESTFORD', now+30, 9),
		('4245', 'WESTFORD', now+40, 11),
		]

	scan_list = []
	for s in TEST_SCANS:
		sr, st, t, d = s
		print time.time(), t
		scan_list.append(Scan(source=sr, station=st, start_time=t,
				      duration=d))

	session = Session(scan_list)
	session.execute()


def run_schedule(schedule, dryrun):
	print 'Running schedule:', schedule
	tree = ElementTree()
	tree.parse(schedule)
	experiment = tree.getroot()
	experiment_name = experiment.attrib['name']
	scans = list(tree.findall('scan'))
	scan_list = []
	for s in scans:
		a = s.attrib
		scan_list.append(Scan(experiment_name=experiment_name,
					source=a['source'],
					station_code=a['station_code'],
					start_time=int(a['start_time']),
					duration=int(a['duration']),
					scan_name=a['scan_name']))
	
	session = Session(scan_list)
	session.execute(dryrun)
	

if __name__ == '__main__':
	parser = optparse.OptionParser()
	parser.add_option('-s', '--schedule', dest='schedule',
			  help='Schedule ')
	parser.add_option('-t', '--test', action='store_true', dest='test',
			  help='Run a test schedule based on current time.',
			  default=False)
	parser.add_option('-d', '--dryrun', action='store_true', dest='dryrun',
			  help='Dryrun of schedule.', default=False)

	(o, a) = parser.parse_args()

	if o.test:
		test()
		sys.exit(0)

	if o.schedule:
		run_schedule(o.schedule, o.dryrun)
		sys.exit(0)
